# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(366, 215)
        self.pushButton = QtWidgets.QPushButton(widget)
        self.pushButton.setGeometry(QtCore.QRect(270, 30, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(widget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 70, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(widget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 30, 241, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 70, 241, 20))
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(widget)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 180, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(8, 110, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(widget)
        self.label_2.setGeometry(QtCore.QRect(80, 110, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(widget)
        self.label_3.setGeometry(QtCore.QRect(150, 110, 61, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 140, 61, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(80, 140, 61, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(150, 140, 61, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_4 = QtWidgets.QLabel(widget)
        self.label_4.setGeometry(QtCore.QRect(220, 110, 61, 20))
        self.label_4.setObjectName("label_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(220, 140, 61, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(widget)
        self.lineEdit_7.setGeometry(QtCore.QRect(290, 140, 61, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_5 = QtWidgets.QLabel(widget)
        self.label_5.setGeometry(QtCore.QRect(290, 110, 61, 20))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(widget)
        self.pushButton.clicked.connect(widget.SelectFile)
        self.pushButton_2.clicked.connect(widget.SelectDir)
        self.pushButton_3.clicked.connect(widget.Start)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.pushButton.setText(_translate("widget", "选择文件"))
        self.pushButton_2.setText(_translate("widget", "保存路径"))
        self.pushButton_3.setText(_translate("widget", "开始"))
        self.label.setText(_translate("widget", "地址起始格"))
        self.label_2.setText(_translate("widget", "地址末尾格"))
        self.label_3.setText(_translate("widget", "原始地址列"))
        self.label_4.setText(_translate("widget", "地址填入列"))
        self.label_5.setText(_translate("widget", "距离填入列"))
